alvos/urls.py
from django.urls import path
from . import views

app_name = 'alvos'
urlpatterns = [
    #views
    path('adicionar/', views.adicionar_alvo, name='adicionar_alvo'),
    path('editar/<int:alvo_id>/', views.edit_alvos, name='edit_alvos'),
    path('deletar/<int:alvo_id>/', views.deletar_alvo, name='deletar_alvo'),
    path('', views.index, name='index'),
]

desafiojoin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('alvos.urls', namespace='alvos')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alvos/models.py
from django.db import models

# Create your models here.

# Modelo de um alvo
class Alvo(models.Model):
    nome = models.CharField(max_length=30)
    latitude = models.DecimalField(max_digits=22, decimal_places=16, blank=True, null=True)
    longitude = models.DecimalField(max_digits=22, decimal_places=16, blank=True, null=True)
    data_expiracao = models.DateTimeField(auto_now=False, auto_now_add=False)

    def __str__(self):
        return self.nome

alvos/forms.py
from django import forms
from .models import Alvo
from django.forms import ModelForm, DateInput

# Formulário usado para criar e editar um alvo
class AlvoForm(forms.ModelForm):
    class Meta:
        model = Alvo
        # datetime-local é um input type do HTML5, formato pra mostrar datetime no campo
        widgets = {
            'data_expiracao': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        }
        fields = ('nome', 'latitude', 'longitude', 'data_expiracao')

    def __init__(self, *args, **kwargs):
        super(AlvoForm, self).__init__(*args, **kwargs)
        # input_formats pra fazer o parser do datetime-local do HTML5 para um datetime field
        self.fields['data_expiracao'].input_formats = ('%Y-%m-%dT%H:%M',)

alvos/views.py
from django.shortcuts import render
from .models import Alvo
from .forms import AlvoForm
from django.contrib import messages
from django.shortcuts import redirect

# Create your views here.


def index(request):
    return render(request, 'alvos/index.html', {})


# View para adicionar um alvo
def adicionar_alvo(request):
    # Se não por POST então envia o form para preencher
    # Se for POST, salva o novo alvo e carrega o index
    if request.method == 'POST':
        adicionar_alvo_form = AlvoForm(data=request.POST)
        if adicionar_alvo_form.is_valid():
            novo_alvo = adicionar_alvo_form.save(commit=False)
            novo_alvo.save()
            return redirect('alvos:index')
        else:
            messages.error(request, 'Preencha o Formulário')
    else:
        adicionar_alvo_form = AlvoForm()

    return render(request, 'alvos/criar_alvo.html', {'adicionar_alvo_form': adicionar_alvo_form})


# View para editar um alvo
def edit_alvos(request, alvo_id):
    # Procura o alvo que vai ser editado
    alvo = Alvo.objects.get(pk=alvo_id)

    # Se for POST, salva os novos dados do alvo
    # Senão, manda os dados do alvo atual para ser editado
    if request.method == 'POST':
        alvo_form = AlvoForm(instance=alvo, data=request.POST)
        if alvo_form.is_valid():
            alvo_form.save()
            return redirect('alvos:index')
        else:
            messages.error(request, 'Preencha o Formulário')
    else:
        alvo_form = AlvoForm(instance=alvo)

    # Manda o alvo.id no contexto pois é necessário caso o usuário queira deletar o alvo
    return render(request, 'alvos/editar_alvo.html', {'alvo_form': alvo_form, 'alvoid': alvo.id})


# View para deletar um alvo
def deletar_alvo(request, alvo_id):
    # Procura o alvo que vai ser deletado e então o deleta
    alvo = Alvo.objects.filter(pk=alvo_id)
    alvo.delete()

    return redirect('alvos:index')

alvos/templates/alvos/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}Alvos - Join{% endblock title %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <link href="{% static 'css/mapa.css' %}" rel="stylesheet">

</head>

<body>

    {% block content %}
    {% endblock content %}


    <script src="https://code.jquery.com/jquery-3.5.1.js"
        integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"
        integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous">
    </script>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js"
        integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous">
    </script>

    <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDJv4aKfW_ZXhgAa19flnVe9sGWaPdbhRA&callback=initMap">
    </script>

    <script src="{% static 'js/mapa.js' %}"></script>
    
</body>

</html>

alvos/templates/alvos/criar_alvo.html
{% extends 'alvos/base.html'%}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<div id="map"></div>

<!-- Modal -->
<div class="modal" id="myModal" role="dialog">
    <div class="modal-dialog">
        <!-- Conteúdo do Modal-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">

                <form method="post">
                    {% csrf_token %}
                    {{ adicionar_alvo_form.as_p }}
                    <label class="labels">Formato da Data: yyyy-mm-dd hh-mm-ss</label>

                    <div class="form-group mt-5">
                        <button type="submit" class="btn btn-primary float-end">
                            Salvar
                        </button>
                    </div>
                </form>

            </div>
            <div class="modal-footer">
                <a href="{% url 'alvos:index' %}" class="btn btn-primary">Fechar</a>
            </div>
        </div>
    </div>
</div>


<script>

let map;

// Função para inicar o mapa
function initMap() {
    var marker;

    //Carrega o mapa
    map = new google.maps.Map(document.getElementById("map"), {
        center: { lat: -0.27832, lng: 8.25031 }, // Mostra o mapa centralizado no globo
        zoom: 3,
    });

    //Coloca os markers no mapa
    {% for alvo in alvos %}
        
        var myLatLng = new google.maps.LatLng({{ alvo.latitude }}, {{ alvo.longitude }});

        marker = new google.maps.Marker({
            position: myLatLng,
            map: map,
            title: '{{ alvo.nome }}',
        });

    {% endfor %}
    
    //Abre o modal com configurações de só fechar no botão
    $('#myModal').modal({backdrop: 'static', keyboard: false});
    $("#myModal").modal('show');
}

</script>

{% endblock content %}

alvos/templates/alvos/editar_alvo.html
{% extends 'alvos/base.html'%}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<div id="map"></div>

<!-- Modal -->
<div class="modal" id="myModal" role="dialog">
    <div class="modal-dialog">
        <!-- Conteúdo do Modal-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">

                <form method="post">
                    {% csrf_token %}
                    {{ alvo_form.as_p }}
                    <label class="labels">Formato da Data: yyyy-mm-dd hh-mm-ss</label>

                    <div class="form-group mt-5">
                        <button type="submit" class="btn btn-primary float-end">
                            Salvar
                        </button>
                    </div>
                </form>

            </div>
            <div class="modal-footer">

                <form action="{% url 'alvos:deletar_alvo' alvoid %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-danger" value='Deletar'>
                </form>
                <a href="{% url 'alvos:index' %}" class="btn btn-primary">Cancelar</a>

            </div>
        </div>
    </div>
</div>


<script>

let map;

// Função para iniciar o mapa
function initMap() {
    var marker;

    map = new google.maps.Map(document.getElementById("map"), {
        // Coloca o centro do mapa onde o alvo está
        center: { lat: parseFloat('{{ alvo_form.latitude.value }}'), lng: parseFloat('{{ alvo_form.longitude.value }}')},
        zoom: 8,
    });
    
    // Colocar todos os alvos no mapa
    {% for alvo in alvos %}
        console.log({{ alvo.latitude }}, {{ alvo.longitude }});
        var myLatLng = new google.maps.LatLng({{ alvo.latitude }}, {{ alvo.longitude }});

        marker = new google.maps.Marker({
            position: myLatLng,
            map: map,
            title: '{{ alvo.nome }}',
        });

    {% endfor %}

    // Mostrar o Modal
    $('#myModal').modal({backdrop: 'static', keyboard: false});
    $("#myModal").modal('show');
}

</script>

{% endblock content %}

alvos/templates/alvos/index.html
{% extends 'alvos/base.html'%}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<div id="map"></div>

<script>
    let map;

    function CreateControl(controlDiv, map) {
        // CSS para arrumar a borda do botão
        const controlUI = document.createElement("div");
        controlUI.style.backgroundColor = "#fff";
        controlUI.style.border = "2px solid #fff";
        controlUI.style.borderRadius = "3px";
        controlUI.style.boxShadow = "0 2px 6px rgba(0,0,0,.3)";
        controlUI.style.cursor = "pointer";
        controlUI.style.marginTop = "22px";
        controlUI.style.marginBottom = "22px";
        controlUI.style.textAlign = "center";
        controlUI.title = "Clique para adicionar um alvo";
        controlDiv.appendChild(controlUI);
        // CSS para controlar o interior do botão
        const controlText = document.createElement("div");
        controlText.style.color = "rgb(25,25,25)";
        controlText.style.fontFamily = "Roboto,Arial,sans-serif";
        controlText.style.fontSize = "16px";
        controlText.style.lineHeight = "38px";
        controlText.style.paddingLeft = "5px";
        controlText.style.paddingRight = "5px";
        controlText.innerHTML = "Adicionar Alvo";
        controlUI.appendChild(controlText);

        // Quando clicar no botão, abrir a página que adiciona um alvo
        controlUI.addEventListener("click", () => {
            window.location.href = "{% url 'alvos:adicionar_alvo' %}"
        });
    }

    // Função para iniciar o mapa
    function initMap() {
        var marker;

        map = new google.maps.Map(document.getElementById("map"), {
            // Centraliza o mapa no centro do globo
            center: { lat: -0.27832, lng: 8.25031 },
            zoom: 3,
        });

        // Cria a DIV pra guardar o botão de criação de um alvo
        // E chama a função CreateControl passando essa div criada
        const centerControlDiv = document.createElement("div");
        CreateControl(centerControlDiv, map);
        map.controls[google.maps.ControlPosition.TOP_CENTER].push(centerControlDiv);

        // Coloca todos os alvos no mapa
        {% for alvo in alvos %}

            var myLatLng = new google.maps.LatLng({{ alvo.latitude }}, {{ alvo.longitude }});

            marker = new google.maps.Marker({
                position: myLatLng,
                map: map,
                title: '{{ alvo.nome }}',
            });

            // Coloca um EventListener em cada alvo para quando clicado abrir a página referente a edição de um alvo
            google.maps.event.addListener(marker, 'click', (function(marker, content) {
                return function () {
                    
                    console.log(marker.title)
            
                    window.location.href = "{% url 'alvos:edit_alvos' alvo.id %}"

                }
            })(marker, window.top));
        {% endfor %}
    }
</script>

{% endblock content %}